apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-repo-creds
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-repo-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
      data:
        url: git@github.com:niklasfrick/homelab.git
        sshPrivateKey: "{{ `{{ .SSH_PRIVATE_KEY }}` }}"
  data:
    - secretKey: SSH_PRIVATE_KEY
      remoteRef:
        key: /argocd/GLOBAL_GITHUB_REPO_ACCESS_SSH_KEY
