apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-creds
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-github-oauth-creds
    creationPolicy: Owner
  data:
    - secretKey: clientID
      remoteRef:
        key: /argocd/OMNI_GITHUB_OIDC_CLIENT_ID
    - secretKey: clientSecret
      remoteRef:
        key: /argocd/OMNI_GITHUB_OIDC_CLIENT_SECRET
