apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
  namespace: bind9
data:
  named.conf: |
    // Global options
    acl internal {
      10.0.0.0/8;
    };

    options {
        directory "/var/cache/bind";
        allow-query { internal; };
        allow-recursion { any; };
        forwarders {
          1.1.1.1;
          1.0.0.1;
        };
    };

    zone "home.balzers.xyz" IN {
        type master;
        file "/var/lib/bind/home.balzers.xyz.zone";
    };

    zone "10.96.10.in-addr.arpa" {
        type master;
        file "/etc/bind/zones/db.10.96.10.in-addr.arpa";
    };

    zone "20.96.10.in-addr.arpa" {
        type master;
        file "/etc/bind/zones/db.20.96.10.in-addr.arpa";
    };


  home.balzers.xyz.zone: |
    $TTL 3600
    $ORIGIN home.balzers.xyz.

    @       IN      SOA     ns.home.balzers.xyz. info.home.balzers.xyz (
                                2024062201  ; serial
                                3600       ; refresh (1 hour)
                                600        ; retry (10 minutes)
                                86400      ; expire (1 day)
                                3600       ; minimum (1 hour)
                                )

            ; NS Records
            IN      NS      ns.home.balzers.xyz.

            ; A Records
    ns      IN      A       10.96.10.80

            ; Additional A Records
    nas-01                IN      A       10.96.10.2
    im                    IN      A       10.96.10.3
    pve-01                IN      A       10.96.10.10
    pbs-01                IN      A       10.96.10.11
    k3s-01                IN      A       10.96.10.20
    k3s-02                IN      A       10.96.10.21
    k3s-03                IN      A       10.96.10.22
    k3s-04                IN      A       10.96.10.23
    k3s-05                IN      A       10.96.10.24
    k3s-06                IN      A       10.96.10.25
    plex-01               IN      A       10.96.20.10
    srv-01                IN      A       10.96.20.11

            ; k3s-trusted traefik A Records
    traefik               IN      A       10.96.10.82
    longhorn              IN      A       10.96.10.82
    prowlarr              IN      A       10.96.10.82
    sabnzbd               IN      A       10.96.10.82
    sonarr                IN      A       10.96.10.82
    radarr                IN      A       10.96.10.82
    bazarr                IN      A       10.96.10.82

  db.10.96.10.in-addr.arpa: |
    $TTL 3600
    $ORIGIN 10.96.10.in-addr.arpa

    @       IN      SOA     ns.home.balzers.xyz. info.home.balzers.xyz (
                                2024062201  ; serial
                                3600       ; refresh (1 hour)
                                600        ; retry (10 minutes)
                                86400      ; expire (1 day)
                                3600       ; minimum (1 hour)
                                )

            ; NS Records
            IN      NS      ns.home.balzers.xyz.

            ; PTR Records
      2      IN      PTR     nas-01.home.balzers.xyz.
      3      IN      PTR     im.home.balzers.xyz.
      10     IN      PTR     pve-01.home.balzers.xyz.
      11     IN      PTR     pbs-01.home.balzers.xyz.
      20     IN      PTR     k3s-01.home.balzers.xyz.
      21     IN      PTR     k3s-02.home.balzers.xyz.
      22     IN      PTR     k3s-03.home.balzers.xyz.
      23     IN      PTR     k3s-04.home.balzers.xyz.
      24     IN      PTR     k3s-05.home.balzers.xyz.
      25     IN      PTR     k3s-06.home.balzers.xyz.
      80     IN      PTR     ns.home.balzers.xyz.
      82     IN      PTR     traefik.home.balzers.xyz.

  db.20.96.10.in-addr.arpa: |
    $TTL 3600
    $ORIGIN 10.96.10.in-addr.arpa

    @       IN      SOA     ns.home.balzers.xyz. info.home.balzers.xyz (
                                2024062201  ; serial
                                3600       ; refresh (1 hour)
                                600        ; retry (10 minutes)
                                86400      ; expire (1 day)
                                3600       ; minimum (1 hour)
                                )

            ; NS Records
            IN      NS      ns.home.balzers.xyz.

            ; PTR Records
      10    IN      PTR     plex-01.home.balzers.xyz.
      11    IN      PTR     srv-01.home.balzers.xyz.