{{- $applicationName := "internal-ingress-nginx" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $applicationName }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: internal-ingress-nginx
  sources:
  - chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    path: ingress-nginx
    targetRevision: {{ index .Values.apps $applicationName "targetRevision" }}
    helm:
      releaseName: internal-ingress-nginx
      valueFiles:
      - $values/apps/{{ $applicationName }}/settings/global-{{ $applicationName }}-helm-values.yaml
      - $values/apps/{{ $applicationName }}/settings/{{ .Values.instance }}/{{ .Values.instance }}-{{ $applicationName }}-helm-values.yaml
  - repoURL: git@github.com:niklasfrick/homelab.git
    ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
