apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: omni
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: omni
  sources:
  - repoURL: git@github.com:niklasfrick/homelab.git
    path: apps/omni/helm/omni
    helm:
      releaseName: omni
      valueFiles:
        - $values/apps/omni/settings/{{ .Values.instance }}/{{ .Values.instance }}-omni-helm-values.yaml
  - repoURL: git@github.com:niklasfrick/homelab.git
    ref: values
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/enforce-version: latest
        pod-security.kubernetes.io/warn: privileged
        pod-security.kubernetes.io/warn-version: latest
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
