---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-balzers-xyz
  namespace: default
spec:
  secretName: home-balzers-xyz-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.home.balzers.xyz"
  dnsNames:
    - "home.balzers.xyz"
    - "*.home.balzers.xyz"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik,longhorn-system,prowlarr,sonarr,radarr,bazarr,sabnzbd" # Control destination namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true" # Auto create reflection for matching namespaces
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "traefik,longhorn-system,prowlarr,sonarr,radarr,bazarr,sabnzbd" # Control auto-reflection namespaces
