apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: holmes-gpt-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: holmes-gpt-secrets
  data:
    - secretKey: anthropic-api-key
      remoteRef:
        key: /base-infrastructure/GLOBAL_ANTRHOPIC_API_KEY
    - secretKey: github-pat
      remoteRef:
        key: /holmes-gpt/HOLMES_GITHUB_PAT
