apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
  namespace: radarr
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
