# Omni configuration
omni:
  endpoint: "https://omni.apps-omni.949x.net"
  serviceAccountKeySecret:
    name: service-account-key
    key: serviceAccountKey

# The IP address where bare-metal machines can reach this provider
# Should be the IP of a node where this pod will run
apiAdvertiseAddress: "10.96.10.101"

# Node selector to ensure the pod runs on a specific node
deployment:
  nodeSelector: {}
    # Example: pin to a specific node
    # kubernetes.io/hostname: node-name

# Extra objects (ExternalSecret for service account key)
extraObjects:
  - |
    apiVersion: external-secrets.io/v1
    kind: ExternalSecret
    metadata:
      name: service-account-key
      namespace: {{ .Release.Namespace }}
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: infisical-secret-store
        kind: ClusterSecretStore
      target:
        name: service-account-key
        creationPolicy: Owner
      data:
        - secretKey: serviceAccountKey
          remoteRef:
            key: /omni/infra-provider/bare-metal/OMNI_SERVICE_ACCOUNT_KEY
