apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: custom-grafana-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-secret-store
    kind: ClusterSecretStore
  target:
    name: custom-grafana-secrets
    template:
      engineVersion: v2
      data:
        GF_SECURITY_ADMIN_USER: "admin"
        GF_SECURITY_ADMIN_PASSWORD: "{{ `{{ .GF_ADMIN_PASSWORD }}` }}"
        GF_AUTH_GITHUB_ENABLED: "true"
        GF_AUTH_GITHUB_ALLOW_SIGN_UP: "true"
        GF_AUTH_GITHUB_CLIENT_ID: "{{ `{{ .GF_GITHUB_CLIENT_ID }}` }}"
        GF_AUTH_GITHUB_CLIENT_SECRET: "{{ `{{ .GF_GITHUB_CLIENT_SECRET }}` }}"
        GF_AUTH_GITHUB_SCOPES: "user:email,read:org"
        GF_AUTH_GITHUB_AUTH_URL: "https://github.com/login/oauth/authorize"
        GF_AUTH_GITHUB_TOKEN_URL: "https://github.com/login/oauth/access_token"
        GF_AUTH_GITHUB_API_URL: "https://api.github.com/user"
        GF_FEATURE_TOGGLES_ENABLE: "externalServiceAccounts"
  data:
    - secretKey: GF_ADMIN_PASSWORD
      remoteRef:
        key: /grafana/{{ .Values.instance }}/GRAFANA_ADMIN_PASSWORD
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
    - secretKey: GF_GITHUB_CLIENT_ID
      remoteRef:
        key: /grafana/{{ .Values.instance }}/GITHUB_CLIENT_ID
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
    - secretKey: GF_GITHUB_CLIENT_SECRET
      remoteRef:
        key: /grafana/{{ .Values.instance }}/GITHUB_CLIENT_SECRET
        conversionStrategy: Default # ArgoCD out of Sync Fix
        decodingStrategy: None # ArgoCD out of Sync Fix
        metadataPolicy: None # ArgoCD out of Sync Fix
