master:
  podSecurityContext:
    fsGroup: 2000

  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

worker:
  podSecurityContext:
    fsGroup: 2000

  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

topologyUpdater:
  enable: true
  createCRDs: true

  resources:
    limits:
      memory: 60Mi
    requests:
      cpu: 50m
      memory: 40Mi

gc:
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 128Mi

prometheus:
  enable: true
