apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-redirect
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: {{ .Values.internalGatewayName }}
    namespace: {{ .Release.Namespace }}
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
