apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.internalGatewayName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      io.cilium/lb-ipam-ips: {{ .Values.internalGatewayIpv4}}
    labels:
      cilium-lb-ip-pool: {{ .Values.internalLbIpPoolName }}
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "{{ .Values.domain }}"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "{{ .Values.domain }}"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: {{ .Values.tlsSecretName }}
