apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: omni-local-lb-ip-pool
spec:
  blocks:
    - start: {{ .Values.ipV4loadbalancerIpPool.start }}
      stop: {{ .Values.ipV4loadbalancerIpPool.stop }}
  serviceSelector:
    matchLabels:
      cilium-lb-ip-pool: omni-local-lb-ip-pool
