{{- if .Values.internalGateway.omniSubdomain.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.internalGateway.omniSubdomain.tlsSecretName | trimSuffix "-tls" }}
  namespace: {{ .Values.internalGateway.namespace }}
spec:
  secretName: {{ .Values.internalGateway.omniSubdomain.tlsSecretName }}
  dnsNames:
    - "{{ .Values.internalGateway.omniSubdomain.domain }}"
  issuerRef:
    {{- toYaml .Values.internalGateway.omniSubdomain.issuerRef | nindent 4 }}
{{- end }}
{{- if .Values.internalGateway.workloadProxy.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.internalGateway.workloadProxy.tlsSecretName | trimSuffix "-tls" }}
  namespace: {{ .Values.internalGateway.namespace }}
spec:
  secretName: {{ .Values.internalGateway.workloadProxy.tlsSecretName }}
  dnsNames:
    - "{{ .Values.internalGateway.workloadProxy.domain }}"
  issuerRef:
    {{- toYaml .Values.internalGateway.workloadProxy.issuerRef | nindent 4 }}
{{- end }}
