apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: cilium-bgp
spec:
  nodeSelector:
    matchLabels:
      bgp: "65020"
  bgpInstances:
    - name: "65020"
      localASN: 65020
      peers:
        - name: "udm-se-65000"
          peerASN: 65000
          peerAddress: {{ .Values.routerIpV4Address }}
          peerConfigRef:
            name: "cilium-peer"
