controller:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    externalTrafficPolicy: Local
  ingressClassResource:
    default: true
    name: "internal-ingress-nginx"
