---
apiVersion: v1
kind: Service
metadata:
  name: internal
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: omni
      port: 8080
      targetPort: omni
      protocol: TCP
    - name: k8s-proxy
      port: 8095
      targetPort: k8s-proxy
      protocol: TCP
    - name: siderolink
      port: 8090
      targetPort: siderolink
      protocol: TCP
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: internal-grpc
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: omni
      port: 8080
      targetPort: omni
      protocol: TCP
    - name: siderolink
      port: 8090
      targetPort: siderolink
      protocol: TCP
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ tpl ($value | toString) $ | quote }}
  {{- end }}
  labels:
    {{- include "omni.labels" . | nindent 4 }}
    {{- if .Values.service.labels }}
    {{- toYaml .Values.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: NodePort
  clusterIP: {{ .Values.service.clusterIP }}
  ports:
    - name: wireguard
      nodePort: {{ .Values.service.siderolink.wireguard.port }}
      port: {{ .Values.service.siderolink.wireguard.port }}
      targetPort: wireguard
      protocol: UDP
  selector:
    {{- include "omni.selectorLabels" . | nindent 4 }}
