apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: grafana-community-oci-repo
type: Opaque
stringData:
  project: infra
  url: ghcr.io/grafana-community/helm-charts
  type: helm
  enableOCI: "true"
