infrastructure_managers:
  hosts:
    im.home.balzers.xyz

plex:
  hosts:
    plex-01.home.balzers.xyz

k3s-trusted:
  hosts:
    k3s-0[1:6].home.balzers.xyz

srv-untrusted:
  hosts:
    srv-01.home.balzers.xyz