tempo:
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 1500Mi

  reportingEnabled: false

  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://prometheus-operated.kube-prometheus-stack.svc.cluster.local:9090/api/v1/write"

  overrides:
    defaults:
      metrics_generator:
        processors:
          - local-blocks

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
