tempo:
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 1500Mi

  reportingEnabled: false

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
