tempo:
  resources:
    requests:
      cpu: 300m
      memory: 500Mi
    limits:
      memory: 1500Mi

  reportingEnabled: false

  overrides:
    defaults:
      metrics_generator:
        processors:
          - service-graphs
          - span-metrics
          - local-blocks

serviceMonitor:
  enabled: true
  interval: 15s
  scrapeTimeout: 10s
